### ISSUE TITLE
ordering of type and argument name in signature?

### ISSUE THREAD

**Issue by ljharb** [lukescott/es-type-hinting#16]
I find it a bit surprising to have `function foo(callback Function)` rather than `function foo(Function callback)` - perhaps it would be useful to enumerate which languages have the type before, and which after, to help decide which would be a more intuitive/less surprising order?

**Comment by lukescott** [comment]
C/C++:

``` c
int add(int a, int b) {
  return a + b;
}
```

Facebook Hack (PHP):

``` php
function add(int $a, int $b): int {
  return $a + $b;
}
```

ActionScript:

``` actionscript
function add(a:int, b:int): int {
  return a + b;
}
```

Go:

``` go
func add(a int, b int) int {
  return a + b
}
// shorter form, both a and b are int
func add(a, b int) int {
  return a + b
}
```

Swift:

``` swift
func add(a: Int, b: Int) -> Int {
  return a + b
}
```
- C/C++ has type on left side, even for the return argument.
- PHP, which has very limited argument types (array & classes) also has type on left side, but because of the `function` keyword can not define a return type on the left side. Facebook Hack adds a return type on the right side. So it is a mix of the two.
- ActionScript has type on right side, but uses a colon `:`. TypeScript, flow, and Swift follow this pattern.
- Go follows a very similar pattern as ActionScript / TypeScript / Flow / Swift, but decides the colon is unnecessary.
- JavaScript, like PHP, has a `function` keyword at the beginning of a function, forcing a return type to be on the right side. Keeping arguments on the same side makes sense.
- One could argue that the variable name is more important than the type, so it should come first.
- With the variable name coming first, a parser knows what it is right away. If a type can come first, it must look-ahead to the next token to determine if the first is a type or variable name (since type hinting is optional). So type on the right side is faster and easier to parse.

**Comment by ljharb** [comment]
Remember, that this needs to work with destructuring syntax. `function foo(a Function = function () {})` vs `function foo(Function a = function () {})` - I find the latter to be far simpler and more intuitive.

**Comment by lukescott** [comment]
Not sure if I would agree any of these are more intuitive than the other:

``` javascript
function foo(a: Function = function() {}) {}
function foo(a Function = function() {}) {}
function foo(Function a = function() {}) {}
```

Any of these "work" with destructuring. The real issue is that type on the right side is faster to parse, and easier for humans to understand: "`john` is a `Human`" not "`Human` `john` is".

Older languages like C/C++ have type on the left. But more modern languages, such as TypeScript, Go, and Swift have it on the right. There is a reason for that.

Given your example, though, couldn't you simply write:

``` javascript
function foo(a = function () {}) {
}
```

In this case isn't `Function` implied by the default?

**Comment by ljharb** [comment]
No, just because it'd be silly to have a multi-type argument, there's lots of functions that do that, so when omitted, it wouldn't be able to be inferred by the language without breaking backwards compatibility.

As for which is more sensible, it's clearly subjective - just like YYYY-MM-DD, I prefer to see first the thing that narrows down what it is - that it's a `Function`, and then that it's named `a` - since the type is far more important than the name when reading a function signature and determining how to call the function (the name is only relevant inside the function)

**Comment by Naddiseo** [comment]
> it's clearly subjective.

I disagree: I would like to add that natural languages favour "noun adjective" [0], so that should be a good argument for the current go-like "thing Type" syntax.

[0][ Matthew S. Dryer. 2013. Order of Adjective and Noun.](http://wals.info/feature/87A#2/18.0/152.8)

**Comment by ljharb** [comment]
You mean like in English, where I'd say "the red car" not "the car red"?

**Comment by Naddiseo** [comment]
The majority of natural languages (~870 vs ~480) prefer "the car red", as in French for example. I suspect the main reason you find `variable Type` strange is because your native language(s) are the opposite (English-like) order, and/or your primary programming languages uses the c++ ordering.

I think that one would get used to the different ordering very quickly, and after a few weeks of using the unfamiliar ordering it would feel natural. I can't cite sources off the top of my head, but there is growing evidence that the brain (at a neurological level) treats artificial/programming languages very similarly (if not the same) to natural languages, thus I think using natural languages as precedent and reasoning when designing a programming language is valid.

**Comment by lukescott** [comment]
I thought it was strange at first too, but after using Go for a while I got used to it, and actually prefer it. Go has a neat trick where `a, b int` means both a and b are ints. That only works with strict typing though (where types are not optional).

**Comment by Naddiseo** [comment]
I think the type hint should be consistently ordered, meaning that a function return type should appear in the same ordering as the parameters. If we assume that, and go with C++/English ordering, you'd end up with situations like:

``` javascript

Number function a(Number arg) {}
// or
function Number a(Number arg) {}

class A {
    Number method() {}
}

let Function a = Number (Number arg) => 1;
// or
Function let a = Number (Number arg) => 1;
```

Since there is two choices for bother the `function` and `let` cases, I think that's reason enough to _not_ use that ordering. The benefit is that a keyword always starts a declaration (`function`, `class`, `let`).

**Comment by ljharb** [comment]
I agree that a keyword should always start the declaration - it sounds like we're talking about:

``` js
function Type name(Type arg)
```

versus

``` js
function name Type(arg Type)
```

?

What would happen with an anonymous typed function? How would the language know that `function Type(Type arg)` is not named "Type"? Note that this would be a problem with both of the scenarios I've stated above.

**Comment by Naddiseo** [comment]
@ljharb, exactly why the type should be after the thing that it modifies:

``` javascript
// "function name(arg Type)" is what the return type is applying to.
function name(arg Type) Type {} 
```

This ordering works with all variations, and is probably why many other languages, which use keywords to introduce declarations, choose `thing Type` and `keyword thing Type`. A few off the top of my head: typescript, rust, python, go, and actionscript.

This proposal isn't really arguing where the type hint should go, it's mostly whether there should be some syntax preceding it, this spec argues there shouldn't be anything. (Typescript and actionscript use `:`, rust and python use `:` and '->'). We are also still debating what exactly the TypeHint can contain (#4), and that topic is something that needs a lot more input from other developers since @lukescott and I have fairly different views on the subject.

**Comment by lukescott** [comment]
Re: what a TypeHint should contain, I'm not sure if we have different views, just that I'm not really sure :).

**Comment by Naddiseo** [comment]
@lukescott, It's also very likely that I don't explain myself clearly. Whatever the case, let's go through each of the possibilities, then get feedback from other people.

**Comment by ljharb** [comment]
I think more than anything else, the combination of 1) optional function names, 2) destructuring, 3) preferring the keyword to start the construct, and 4) maintaining consistency between vars/function returns, and function arguments, is pretty convincing - and when all these are considered, the aesthetic argument of "first" or "last" seems like it ends up being moot (which is a good thing, since both are highly subjective, both have examples of other human and computer languages using them, and could be long debated).

If, for example, this aligns with the current proposal, then I think you might have a solid case:

``` js
let foo Function = function bar(a = 'foo' String, b Number, {c = [3] Array[Number], d = /a/g RegExp} = {} Object, ...args Array[String, Number]) String {
  return a + b + c + d + args;
};
```

Would built in primitive wrappers be special cased to allow for primitives as well? (probably a different issue question)

**Comment by Naddiseo** [comment]
@ljharb, close. Currently, the spec has the typehint placed before the `=` assignment operator, otherwise it could potentially get lost if the RHS spans off the edge of the screen.

Regarding what the type hint is, it's still under discussion (#4 and #9), you're welcome to jump in and offer feedback.

**Comment by lukescott** [comment]
For reference, that would look like this:

``` javascript
let foo Function = function bar(a String = 'foo', b Number, {c Array[Number] = [3], d RegExp = /a/g} Object = {}, ...args Array[String, Number]) String {
  return a + b + c + d + args;
};
```

Although I'm not sure we'll do `Array[...]`. That becomes hard to enforce (check every value). There is a proposal out there for adding typed arrays already. So it would likely be something like Int32Array.

**Comment by ljharb** [comment]
Sounds good. I still prefer LHS, but I think I've been convinced that it's not an issue of aesthetics in either direction at this point.

Thanks!
